apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-rbnd
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0038-tenant/tkrw-pr712-0075-0038-app/devfile-sample-rbnd@sha256:dec13e274b2185d5e62f8c5c2a145a91ee5b426fbb4c1e8c250af28263dbc676
        name: my-nodejs
        resources: {}
status: {}
